; Not sure what this was supposed to do. Looks like a testing ground
; of sorts for bunching windows together in the taskbar (which is something I
; tried to do with wfreerdp)

#MaxThreadsPerHotkey 2
#SingleInstance Force
#persistent

#Include KnirchLib\Reloader.ahk
#Include KnirchLib\WinHacks.ahk

DetectHiddenText, On

msgbox, FOOBAR %hwnd%
szAppId:="Microsoft.AutoGenerated.{D6928545-D913-47DA-0E69-935182A160A6}"
iD:="{6D809377-6AF0-444B-8957-A3773F02200E}\AutoHotkey\AutoHotkey.exe"

iD:="SHUTUP SHUTUP SHUTUP SHUTUP"

msgbox, % GetOwnHWND()

WinGet, hwnd, ID, ahk_exe wfreerdp.exe
SetWinAppID(GetOwnHWND(), iD)
SetWinAppID(hwnd, iD)

sleep 100000
exit
